#!/bin/bash

mkdir -p data/imagenet_weights
cd data/imagenet_weights
wget -v http://download.tensorflow.org/models/resnet_v1_101_2016_08_28.tar.gz
tar -xzvf resnet_v1_101_2016_08_28.tar.gz
mv resnet_v1_101.ckpt res101.ckpt
cd ../..

cd lib
make
make clean
cd ..

cd data
git clone https://github.com/pdollar/coco.git
cd coco/PythonAPI
make
cd ../../..